### ISSUE TITLE
Support for calling iterateForPromise n times

### ISSUE THREAD

**Issue by tusharmath** [charleshansen/mock-promises#11]
Sometimes I just want to call the `iterateForPromise` method `n` times. It would be a good idea if I am able to pass an additional argument which iterates over `n` number of times.

```js
mockPromises.iterateForPromise(promise, 4); //Should be equivalent to calling the method 4 times
```

**Comment by rdy** [comment]
+1 I'd love to see this feature

**Comment by charleshansen** [comment]
There is now a `tick` function that will execute `n` times for all promises. Do you still want this for `iterateForPromise`? I've found myself not using that function as much.
