### ISSUE TITLE
Chaining does not recurse properly

### ISSUE THREAD

**Issue by vsa** [charleshansen/mock-promises#14]
When iterating over a resolved promise, only the first subsequent thenable is executed instead of recursing into all resolved thenables. This works as expected in the browser, but the test below fails:

```javascript
it('chains correctly more than one level deep', function() {
  promise1 = PromiseWrapper('foo');
  promise2 = PromiseWrapper('bar');
  promise3 = PromiseWrapper('baz');
  var promisedValue1 = 'not resolved';
  var promisedValue2 = 'not resolved';
  var promisedValue3 = 'not resolved';
  promise1.then(function(value) {
    promisedValue1 = value;
    return promise2;
  }).then(function(value) {
    promisedValue2 = value;
    return promise3;
  }).then(function(value) {
    promisedValue3 = value;
  });

  mockPromises.executeForPromise(promise1);
  mockPromises.executeForPromise(promise2);
  mockPromises.executeForPromise(promise3);
  mockPromises.iterateForPromise(promise1);		  
  expect(promisedValue1).toEqual('foo');
  expect(promisedValue2).toEqual('bar');
  expect(promisedValue3).toEqual('baz');
});
```

**Comment by charleshansen** [comment]
That looks like intended behavior. iterateForPromise is only supposed to go down one level of recursion each time you call it. It seemed that if I let it go all the way down the chain, you lose too much control of the situation. If you add two more `mockPromises.iterateForPromise(promise1)`, then it should pass. I also don't think you need those original 3 `executeForPromise`, but I haven't run it myself.
