### ISSUE TITLE
Native Promise.all does not work with await*

### ISSUE THREAD

**Issue by charleshansen** [charleshansen/mock-promises#17]
```js
it('works with async/await', function() {
    var result;
    async function foo() {
      result = await* [Promise.resolve('a'), Promise.resolve('b')];
    }
    foo();
    MockPromises.executeForResolvedPromises();
    MockPromises.executeForResolvedPromises();
    expect(result).toEqual(['a', 'b']);
  });
```
 
This test fails Using babel / regenerator to transpile the await*. For some reason, the promise resolves to a promise that resolves to an array. It should just resolve to an array. It works fine for es6-promises. Need to figure out why Regenerator thinks it needs to wrap an extra promise here.

**Comment by rdy** [comment]
I think I might be seeing this as well in the case when a then of a promise returns another promise that is resolved or rejected differently than the original.

It sounds like a similar case, but if it is indeed separate I can create a different issue for this.

**Comment by rdy** [comment]
```js
    it('resolves a promise resolved with constructor resolve', function() {
      var doneSpy = jasmine.createSpy('done');
      promise1.then(function() {
        return nativeLibrary.PromisesWrapper('bar');
      }).then(doneSpy);
      mockPromises.executeForResolvedPromises();
      mockPromises.executeForResolvedPromises();
      mockPromises.executeForResolvedPromises();
      expect(doneSpy).toHaveBeenCalledWith('bar');
    });
```

**Comment by charleshansen** [comment]
await* isn't a thing anymore
