### ISSUE TITLE
Provide a function that ticks until all promises have results

### ISSUE THREAD

**Issue by lukeapage** [charleshansen/mock-promises#18]
I keep finding myself writing
```
mockPromises.tick(100);
```
during integration tests, to resolve all promises in underlying logic. It would be good to have a method that ticks until all promises are resolved, if you know that is going to happen.

**Comment by charleshansen** [comment]
I've intentionally not included this method in the library because I find it leads to bad code. Asynchronous coding is hard enough that I always want to know how many layers of promises I am waiting for before I get the final result I want. People somewhat frequently ask for it and then seem happy without it once they get used to understanding their code better.

That said, I always hate library owners who do this kind of thing to me, so I'll probably add it in eventually and call it `dangerouslyTick` or something like that. It isn't very high priority for me, though I will take a pr if you really want it soon.

**Comment by lukeapage** [comment]
Thanks. I can see how this is true for strict unit testing, its just we
have a setup where we provide mock data and then have a model layer based
on that and a presenter on that.. we test the view controller in a
integration way that tests all the layers below it.. and I dont want a
change in the model layer to require a change in the view controller tests.
I find this style of test valuable in addition to something stricter
testing a single function or class where you do want to know more about
which promises are resolved :)

I will consider a pr when I have time.

**Comment by charleshansen** [comment]
I remembered the other reason I haven't added anything yet. I think that `tick(100)` fills all my needs already. It has all the functionality you want, but it feels gross enough that you won't use it unless you have to. It will go through an empty loop 99 times, but this shouldn't be a significant performance hit.

As an aside, what framework are you using? Most users that I am aware of are either React (where the asynchrony in the model layer does not matter for view tests) or Node (which does not have views at all) or sometimes Backbone (but this is way less popular now).

**Comment by lukeapage** [comment]
> As an aside, what framework are you using? Most users that I am aware of are either React (where the asynchrony in the model layer does not matter for view tests) or Node (which does not have views at all) or sometimes Backbone (but this is way less popular now).

At the moment its a large monster, not really using any framework. We are moving to react - we envisage mainly needing this use-case for the legacy code :)

I see your point about `tick(100)` - we can just live with that.

**Comment by rdy** [comment]
It would be superior to not use this library and just use async mode in your tests if you don't care about when promises get resolved. This library's primary use case is being able to test things in a synchronous manner. 

I personally prefer to know how many real ticks are needed.

**Comment by lukeapage** [comment]
I prefer sync tests.. everytime i have async tests they are not very
maintainable.. they are unreliable and people miss side effects and a
refactor that shouldnt break tests, does.
