### ISSUE TITLE
API for executing all resolved promises callbacks to the end

### ISSUE THREAD

**Issue by jeron-diovis** [charleshansen/mock-promises#24]
I read your [policies](https://github.com/charleshansen/mock-promises#promise-resolution-policy). Full control over invoking each callback is a powerful feature. But I'm not sure that such detailing is what is required in most cases. Promises resolves/rejects over time – so, probably, one would like to shift time (via [sinon fake timers](http://sinonjs.org/docs/#clock), for example) and then check whether his promise is resolved/rejected at that moment.

On my view, such method should work like `iterateForPromises`, which takes all existing contracts, and not just executes the first available contract in branch, but keeps diving tree while new levels exist.

I managed to implement such behaviour with very simple code (although it's rather a kind of hack):

``` js
MockPromises.getPendingPromisesCount = function() {
  return this.contracts.filter(x => !x._executed).length
}

MockPromises.run = function() {
  let prev, curr
  do {
    prev = this.getPendingPromisesCount()
    this.contracts.executeForResolvedPromises()
    curr = this.getPendingPromisesCount()
  } while (prev !== curr)
}
```

And it works like this:

``` js
function FakeAsync(cb) {
  const clock = sinon.useFakeTimers()
  global.Promise = MockPromises.getMockPromise(Promise)
  try {
    cb(ms => {
      clock.tick(ms)
      MockPromises.run()
    })
  } finally {
    MockPromises.reset()
    global.Promise = MockPromises.getOriginalPromise()
    clock.restore()
  }
}

FakeAsync(tick => {
  const log = str => x => { console.log(str, x); return x; }
  const x2 = x => x * 2;

  const p = new Promise(res => {
    setTimeout(res, 100, 1)
  })

  p.then(log("cb1:")).then(x2)
    .then(log("cb2:")).then(x2)
    .then(x => new Promise(res => {
      setTimeout(res, 100, x)
    }))
    .then(log("cb3:")).then(x2)
    .then(log("cb4:"))

  console.log("-- 50 ms --")
  tick(50)
  console.log("-- 100 ms --")
  tick(50)
  console.log("-- 200 ms --")
  tick(100)
})

// output is:
// -- 50 ms --
// -- 100 ms --
// cb1: 1
// cb2: 2
// -- 200 ms --
// cb3: 4
// cb4: 8
```

So, the question is: does it make sense and how about adding such a functionality to core?

**Comment by charleshansen** [comment]
Agreed that it would not be difficult to add the functionality, but I would still prefer not to. I believe your request is similar to issue #18, if you want more context. Your use case is a little different because you are combining multiple mocks together in a generic function. I think in that situation I tend to use jasmine in async mode, but your way could work too. I'm still open to the idea of adding the functionality but giving it a bad name so that it is clear you shouldn't use it most of the time. Let me know what you think after reading the other issue.

**Comment by jeron-diovis** [comment]
So, your position is, in short, "you don't need this feature, because it means that you badly understand what your code really does"? 

Well, in general, I agreed. It's reasonable argument, when you testing **promises** itself. When you always have direct access to promise you want to test (so most of your API is designed to deal with particular promise). Actually, in most of such cases I may not need to mock promises at all, and just use nice tools like [chai-as-promised](http://chaijs.com/plugins/chai-as-promised/).

The devil is, as usual, in details. My code uses 3-party reactive streams library. I provide to that lib a function, returning a promise, and lib creates a stream from it. And inside lib can do with created promises whatever it wants, so I **really have no idea what's going on there**. It's a black box. I don't know how many layers of promises I should wait for. I don't have access to specific promise – and, actually, I don't care of it at all. I'm testing a **stream**, not a promise. Promise in this case is just another way to define async operation – which, unfortunately, I can't mock with sinon, so I need another tool.

It's true that `tick(100)` on practice will solve the task. But do you agree that case itself is a bit more deep than just bad understanding of own code, and so deserves a special API method?

**Comment by charleshansen** [comment]
Fair points, third party code with lots of promises is annoying with just `tick`. I guess I'll add something then. In the meantime, feel free to use your patch or `tick(100)` without judgement :).

On a side note, I'm not sure which streams your code is using, but I've had some success mocking out the `nextTick` function on streams when I want them to go to the next element in a synchronous manner. This won't fix the problem you are describing, but may be useful.

**Comment by charleshansen** [comment]
I just published version 0.7 with a 'tickAllTheWay' function. I'll add it to the readme later, but you can start using it if you want.

**Comment by jeron-diovis** [comment]
Works good, thank you.

**Comment by charleshansen** [comment]
Added the readme finally, closing.
